"""empty message

Revision ID: 946aa84e5c48
Revises: b1c92c2fdda6
Create Date: 2021-08-16 10:16:29.183197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946aa84e5c48'
down_revision = 'b1c92c2fdda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
