"""empty message

Revision ID: b1c92c2fdda6
Revises: 
Create Date: 2021-08-16 10:13:48.687739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c92c2fdda6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product') as batch_op:
        batch_op.drop_column('description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
